name: Getting Started

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  getting_started:
    strategy:
      fail-fast: false
      matrix:
        include:
          - env-prefix: PY39_LINUX
            os: ubuntu-latest
            python-version: 3.9

          - env-prefix: PY313_LINUX
            os: ubuntu-latest
            python-version: 3.13

          - env-prefix: PY313_WINDOWS
            os: windows-latest
            python-version: 3.13

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: read

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: snowddl
      SNOWFLAKE_AUTHENTICATOR: workload_identity
      SNOWFLAKE_WORKLOAD_IDENTITY_PROVIDER: OIDC
      SNOWFLAKE_AUDIENCE: snowflakecomputing.com
      SNOWFLAKE_ENV_PREFIX: ${{ matrix.env-prefix }}

    steps:
      - name: Enable longpaths
        run: git config --global core.longpaths true

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SnowDDL
        run: pip install -e .

      - name: Install Snowflake CLI
        run: pip install snowflake-cli

      - name: Get Workload Identity Token
        run: echo "SNOWFLAKE_WORKLOAD_IDENTITY_TOKEN=$(snow auth oidc read-token --type=github)" >> "$GITHUB_ENV"

      - name: Show Workload Identity Token
        run: echo "$SNOWFLAKE_WORKLOAD_IDENTITY_TOKEN"

      - name: "Cleanup"
        run: snowddl -c sample01_01 --apply-unsafe destroy

      - name: "Apply sample01_01, run 1"
        run: snowddl -c sample01_01 --apply-unsafe apply

      - name: "Apply sample01_01, run 2"
        run: snowddl -c sample01_01 --apply-unsafe apply

      - name: "Apply sample01_02, run 1"
        run: snowddl -c sample01_02 --apply-unsafe apply

      - name: "Apply sample01_02, run 2"
        run: snowddl -c sample01_02 --apply-unsafe apply

      - name: "Apply sample02_01"
        run: snowddl -c sample02_01 --apply-unsafe --apply-masking-policy --apply-row-access-policy apply

      - name: "Apply singledb"
        run: snowddl-singledb -c sample02_01 --config-db=TEST_DB --target-db=ANOTHER_DB --apply-unsafe --apply-masking-policy --apply-row-access-policy apply
