name: Pytest

on:
  push:
    paths:
      - "**.py"
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  pytest:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: snowddl_test
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ENV_PREFIX: PYTEST

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install
        run: pip install -e .[dev]

      - name: Run pytest
        run: test/run_test_full.sh
